### ISSUE TITLE
Cannot install package via opam.

### ISSUE THREAD

**Issue by zoj613** [dbuenzli/bytesrw#1]
The README suggests that this project can be installed via opam, but `opam install bytesrw` errors with `No package named bytesrw found`. I  searched on the [opam site](https://opam.ocaml.org/packages/) and this package does not show up in the search index. Is there something that can be done about this?

**Comment by dbuenzli** [comment]
I'm afraid not. You have to wait. Hopefully this will happen at least by december. If you feel adventurous:

    opam pin add git+https://erratique.ch/repos/bytesrw.git

**Comment by zoj613** [comment]
Thanks for the suggestion. Since this project contains Gzip and Zstd compression/decompression in one package, i'll go ahead and install it via pinning.

PS: please also add CRC32C hashing if possible.

**Comment by dbuenzli** [comment]
> PS: please also add CRC32C hashing if possible.

Do you have any library in mind ? Linux distribution support for this [`crc32c`](https://repology.org/project/crc32c/versions) library seems spotty. It also feels a bit silly and quite a lot of work to have only support for that particular CRC32 polynomial.

**Comment by zoj613** [comment]
> > PS: please also add CRC32C hashing if possible.
> 
> Do you have any library in mind ? Linux distribution support for this [`crc32c`](https://repology.org/project/crc32c/versions) library seems spotty. It also feels a bit silly and quite a lot of work to have only support for that particular CRC32 polynomial.

There is [rhash](https://repology.org/project/rhash/versions) and [gsutil>=4.4](https://repology.org/project/gsutil/versions), but it appears they are just commandline programs. I am currently using https://github.com/mirage/checkseum but I'd much rather have most of the functionality I need under one package where possible.

**Comment by dbuenzli** [comment]
https://github.com/ocaml/opam-repository/pull/26990

**Comment by zoj613** [comment]
> > > PS: please also add CRC32C hashing if possible.
> > 
> > 
> > Do you have any library in mind ? Linux distribution support for this [`crc32c`](https://repology.org/project/crc32c/versions) library seems spotty. It also feels a bit silly and quite a lot of work to have only support for that particular CRC32 polynomial.
> 
> There is [rhash](https://repology.org/project/rhash/versions) and [gsutil>=4.4](https://repology.org/project/gsutil/versions), but it appears they are just commandline programs. I am currently using https://github.com/mirage/checkseum but I'd much rather have most of the functionality I need under one package where possible.

@dbuenzli Have you given this request any thought lately? I still believe it would be a nice to-have

**Comment by dbuenzli** [comment]
Not more than what I previously said.

**Comment by dbuenzli** [comment]
Note that an alternative may be to simply do it in OCaml. See for example [this code](https://github.com/dbuenzli/zipc/blob/b5f1664e7cc76f12b88e37e6a1feb2f95a8c17d7/src/zipc_deflate.ml#L106-L164) in `zipc`.
