### ISSUE TITLE
Wrong bounds checks in slice constructors

### ISSUE THREAD

**Issue by amongonz** [dbuenzli/bytesrw#4]
The bound checks for `Slice.make` and `make_or_eod` both allow invalid slices and disallow invalid ones:

```ocaml
(* This should fail, returns an invalid slice instead. *)
Bytes.Slice.make (Bytes.of_string "foo") ~first:2 ~length:2;;

(* This should succeed, raises Invalid_argument instead. *)
Bytes.Slice.make_or_eod Bytes.empty ~first:0 ~length:0;;
```

The correct error condition should be equivalent to `not (0 <= first && 0 < length && first + length <= len)` for `make`, and the same with `0 <= length` for `make_or_eod`.

**Comment by dbuenzli** [comment]
There were also problems with `Slice.sub[_or_eod]`. 

Thanks for suggesting the condition which is much clearer than what I had there and makes indexing behave like `Bytes.sub` (for better or worse) on `_or_eod` versions.
